AddonId: SteamGridDB_Playnite_Metadata
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-08
    PackageUrl: https://github.com/cooperate/SteamGridDBMetadata/releases/download/1.0/SteamGridDB_Playnite_Metadata_1_0.pext
    Changelog:
      - Playnite 9 support
      - Added localizations support
      - Added button in settings page to open SteamGridDB API Key page